### ISSUE TITLE
Some Suggestion

### ISSUE THREAD

**Issue by zxp19821005** [FrostBreker/AeroBrowser#26]
Thank you for the project first!
I've shifted it to ArchLinux AUR: [aero-browser](https://aur.archlinux.org/packages/aero-browser) and [aero-browser-git](https://aur.archlinux.org/packages/aero-browser-git).
I've some suggestions:
1. I think change the project name to "AeroBrowser" is a good idea,so many project's name was called `aero`
2. When I run the program,there was no project icon dispaly in the system bar,just an unknown program icon.
3. When you publish the packages,will you please add the Linux version?
4. Add AppImage version,it has good compatibility for lots of Linux Distrobutions.

**Comment by FrostBreker** [comment]
Hello, thanks for your suggestion! I will try to add the compatibility for Linux, the app is still in alpha and take times to be developed I'm only working on it in my freetime but I will try to do more update ^^
